#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello_page:
    path:         /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: hello_page.html.twig

test:
    path:         /test
    controller:   App\Controller\TestController::number